---
dist: jammy
language: python
python: 3.9
services:
- docker
install:
  - pip install pipenv
  - pipenv sync
env:
  jobs:
    - MOLECULE_DISTRO=debian:bookworm-slim
    - MOLECULE_DISTRO=debian:bullseye-slim
    - MOLECULE_DISTRO=debian:buster-slim
script:
  - pipenv run molecule test --all --destroy always

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
